#!/bin/R
source("../treemix-1.13/src/plotting_funcs.R")

# Treemix Plot

# # # 
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.0.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.0")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.1.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.1")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.2.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.2")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.3.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.3")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.4.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.4")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.5.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.5")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.6.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.6")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.7.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.7")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.8.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.8")
dev.off()

pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.0.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.0", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.1.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.1", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.2.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.2", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.3.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.3", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.4.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.4", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.5.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.5", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.6.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.6", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.7.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.7", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.8.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k100.treemix.8", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()

pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.0.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.0")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.1.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.1")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.2.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.2")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.3.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.3")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.4.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.4")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.5.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.5")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.6.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.6")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.7.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.7")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.8.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.8")
dev.off()

pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.0.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.0", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.1.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.1", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.2.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.2", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.3.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.3", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.4.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.4", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.5.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.5", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.6.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.6", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.7.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.7", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.8.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k200.treemix.8", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()

pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.0.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.0")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.1.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.1")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.2.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.2")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.3.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.3")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.4.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.4")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.5.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.5")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.6.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.6")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.7.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.7")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.8.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.8")
dev.off()

pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.0.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.0", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.1.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.1", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.2.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.2", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.3.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.3", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.4.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.4", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.5.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.5", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.6.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.6", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.7.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.7", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.8.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k500.treemix.8", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()

pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.0.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.0")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.1.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.1")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.2.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.2")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.3.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.3")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.4.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.4")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.5.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.5")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.6.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.6")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.7.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.7")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.8.admixgraph.pdf")
plot_tree("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.8")
dev.off()

pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.0.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.0", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.1.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.1", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.2.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.2", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.3.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.3", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.4.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.4", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.5.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.5", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.6.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.6", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.7.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.7", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
pdf("../results/graphs/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.8.residuals.pdf")
plot_resid("../results/treemix/All_pops_Sbal_VCF.filter.99misd.maf5.SNPs.rehead_k1000.treemix.8", "S_bal_TreeMix_joaquin_unpruned_sample_names.txt")
dev.off()
